### ISSUE TITLE
printf invalid number

### ISSUE THREAD

**Issue by zx9r** [Deekee62/bos_accounting#12]
```
~/bos_accounting$ ./bos_accounting.sh
2021-09-23    18:35:26    044263584    17181499   ./bos_accounting.sh: line 82: printf: 38.81: invalid number
 38,00%     13 ppm    0 ppm    7 ppm   00000588    -00000000    -00000265    00000323

```

38.81 is the value of $f_pcrouted (calculated with bc)

However printf doesn't like it

**Comment by Deekee62** [comment]
You could have a locale problem, and it wasn't expecting a period. Try:

LC_NUMERIC="en_US.UTF-8" printf "%#6.2f%%" $f_pcrouted;

**Comment by Deekee62** [comment]
Still having problems?
