### ISSUE TITLE
"./bos_accounting.sh >> bos_accounting.log" not working properly

### ISSUE THREAD

**Issue by MaxDruthers** [Deekee62/bos_accounting#15]
When I try "./bos_accounting.sh >> bos_accounting.log", I get this in return...

err: 
  - 503
  - ExpectedCommitmentTypeInChannelMessage

err: 
  - 503
  - ExpectedCommitmentTypeInChannelMessage

./bos_accounting.sh: line 53: 100/(10#/10#01932163): division by 0 (error token is "(10#/10#01932163)")
./bos_accounting.sh: line 56: 1000000/0: division by 0 (error token is "0")
./bos_accounting.sh: line 60: 10#/10#: division by 0 (error token is "10#")
./bos_accounting.sh: line 60: 1000000/: syntax error: operand expected (error token is "/")
./bos_accounting.sh: line 64: 1000000/(10#/(10#00000162-10#-10#)): division by 0 (error token is "(10#/(10#00000162-10#-10#))")

**Comment by Deekee62** [comment]
It seems that the command `bos balance --detailed` fails and doesn't return any value, please check your bos install
