### ISSUE TITLE
Div by zero error

### ISSUE THREAD

**Issue by kpshukla** [Deekee62/bos_accounting#7]
Div by zero error
line 53: division by 0 error

Line 53:  f_pcrouted=`printf "%0.2f" $((100/(10#$a_local/10#$b_routed)))`

Answer should be 109.87 in the test case.

**Comment by Deekee62** [comment]
Unfortunately I can not reproduce the error, can you provide the values of variable $a_local and b_routed?

**Comment by kpshukla** [comment]
It is fixed now.
