### ISSUE TITLE
f_pcrouted bad calculated or printed

### ISSUE THREAD

**Issue by zx9r** [Deekee62/bos_accounting#9]
>                       a_local    b_routed   percent
> 2021-09-19    23:21:38    040263593    21775661    100,00% 
> 2021-09-19    23:55:11    040263593    19875601    50,00% 
> 2021-09-20    23:55:11    040263603    17276403    50,00% 
> 2021-09-21    17:58:15    040263681    15653842    50,00%

As you can see percent is being bad calculated or at least bad printed.

I can't fix it because I dont know bash scripting syntax but i can see where is calculated:

> f_pcrouted=`printf "%0.2f" $((100/(10#$a_local/10#$b_routed)))`

And where is printed:

> printf "    "$a_local"    "$b_routed"    "$f_pcrouted"%%";

**Comment by BhaagBoseDK** [comment]
see latest PR. #10

**Comment by zx9r** [comment]
Pulled and checked. Still same result:

> 2021-09-21    19:32:08    040263681    15411409    50,00%

**Comment by BhaagBoseDK** [comment]
made the fix, the calculation is integer for now so 38.27% will appear as 38.00%
I can do another fix later on which will bring back the dependency on bc.

**Comment by BhaagBoseDK** [comment]
#11 now contain support for bc. if /usr/bin/bc exist it is used to calculate floating points (else integer)

**Comment by Deekee62** [comment]
Problem is fixed.
